# Disable Cache
cache deny all

# Drop X-Forwarded-For header
forwarded_for delete

# Block all private IP ranges (including APIPA 169.254)
acl denied_dst dst 127.0.0.1/8
%{ for cidr in denied_cidrs ~}
acl denied_dst dst ${cidr}
%{ endfor ~}
http_access deny denied_dst

# Most of our network stack is not configured for IPv6 but lets make sure we have obvious ones covered in case that changes...
acl denied_ipv6 dst fd00::/8  # link-local
acl denied_ipv6 dst fe80::/10 # private
http_access deny denied_ipv6

# Block cache manager access
acl manager proto cache_object
http_access deny manager

# Allow access from all networks
# This effectively allows all traffic unless it has already been denied
acl allowed_src src all
http_access allow allowed_src

# Deny all access that hasn't matched an explicit allow (we should never get here ... but just in case)
http_access deny all

# Log to stdout
logfile_rotate 0

# Server settings
http_port 3128
coredump_dir /var/spool/squid
