module "release" {
  source = "../../helm-release"

  name             = local.name
  description      = "karpenter Helm Chart for Node Autoscaling"
  chart            = local.name
  repository       = "public.ecr.aws/karpenter"
  chart_version    = var.chart_version
  namespace        = var.namespace
  timeout          = var.timeout
  create_namespace = var.create_namespace
  enable_oci       = true

  manage_via_argocd = var.manage_via_argocd
  argocd_app_config = merge({
    ignore_differences = [
      # Ignore autogenerated certificates
      {
        kind = "Secret"
        name = "karpenter-cert"
        jsonPointers : ["/data"]
      },
      # Ignore Webhook Changes
      {
        group = "admissionregistration.k8s.io"
        kind  = "MutatingWebhookConfiguration"
        name  = "defaulting.webhook.provisioners.karpenter.sh"
        jsonPointers : ["/webhooks"]
      }
    ]
  }, var.argocd_app_config)

  additional_helm_config = var.helm_config

  values = [
    templatefile("${path.module}/templates/values.yaml", {
      eks_cluster_id            = var.eks_cluster,
      eks_cluster_endpoint      = var.eks_cluster_endpoint,
      node_iam_instance_profile = aws_iam_instance_profile.karpenter.name
      role_arn                  = module.irsa.irsa_iam_role_arn
    })
  ]
}
