redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

%{ if !OKTA_ENABLE ~}
dex:
  enabled: false
%{ endif ~}

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: ${ENABLE_INGRESS}
    ingressClassName: ${INGRESS_CLASS}
    hosts:
      - ${UI_DOMAIN}
  extraArgs:
    - --insecure
  config:
    accounts.admin: apiKey, login
    url: https://${UI_DOMAIN}
%{ if OKTA_ENABLE ~}
    dex.config: |
      logger:
        level: debug
        format: json
      connectors:
      - type: saml
        id: okta
        name: Okta
        config:
          ssoURL: ${OKTA_SSO_DOMAIN}
          caData: |
            ${OKTA_CA_BASE64}
          redirectURI: https://${UI_DOMAIN}/api/dex/callback
          usernameAttr: email
          emailAttr: email
          groupsAttr: group
%{ endif ~}
  rbacConfig:
%{ if OKTA_ENABLE ~}
    scopes: '[email,groups]'
    policy.default: role:readonly
%{ endif ~}
    policy.csv: |
${DATA_PERMISSIONS}
${POLICIES}
%{ if OKTA_ENABLE ~}
${OKTA_GROUPS}
      g, ${OKTA_ADM_GROUP}, role:admin
%{ endif ~}

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
