settings:
  aws:
    defaultInstanceProfile: ${node_iam_instance_profile}
    clusterName: ${eks_cluster_id}
    clusterEndpoint: ${eks_cluster_endpoint}
serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": ${role_arn}
