resources:
  - base.yaml
patches:
  - target:
      version: v1
      kind: Deployment
      name: istio-ingressgateway
    # checkov:skip=CKV_SECRET_6:False positive (these are not secret values)
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: ingressgateway-certs
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              # checkov:skip=CKV_SECRET_6:False positive (these are not secret values)
              secretProviderClass: "ingressgateway-certs" #gitleaks:allow
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: ingressgateway-certs
          mountPath: /etc/istio/ingressgateway-certs
          readOnly: true
